gitCheatSheet.md

Added 10 point in gitCheatSheet about push changes

Added 10 point in gitCheatSheet about push changes

---

Portfolio/styles.css

Consolidation: Similar styles were combined into a single class (e.g., general section styles).
Reduced Redundancy: Common styles were removed from specific selectors where possible.
Streamlined Selectors: Used more efficient selectors and shorthand properties for cleaner code.
Consistency: Ensured consistent spacing and font styles across different sections.

Reduced Redundancy

---

lms/.gitignore
lms/.mvn/wrapper/maven-wrapper.properties
lms/mvnw
lms/mvnw.cmd
lms/pom.xml
lms/src/main/java/com/example/lms/LmsApplication.java
lms/src/main/java/com/example/lms/controller/BookController.java
lms/src/main/java/com/example/lms/dto/BookDTO.java
lms/src/main/java/com/example/lms/entity/Book.java
lms/src/main/java/com/example/lms/manager/BookManager.java
lms/src/main/java/com/example/lms/mapper/BookMapperImplementation.java
lms/src/main/java/com/example/lms/repository/BookRepository.java
lms/src/main/java/com/example/lms/request/BookRequest.java
lms/src/main/java/com/example/lms/response/BookResponse.java
lms/src/main/java/com/example/lms/service/BookService.java
lms/src/main/resources/application.properties
lms/src/test/java/com/example/lms/LmsApplicationTests.java

Included a well architectured LMS in java and Spring using PostgreSql.

Added a Library Management System in Java and Springboot

---

Sorting/HeapSort.java

Created Heap sort method in java with necessary comments,time complexity analysis and validation

Created HeapSort.java

---

Sorting/InsertionSort.java

Created Insertion sort method in java with time complexity analysis and validation

Created InsertionSort.java

---

Sorting/BubbleSort.java

Created bubble sort method in java with clean comments,validation and time&space complexity analysis

Created BubbleSort.java

---

Sorting/Quicksort.java

This version is structured to be easily understandable and includes methods to facilitate user interaction. please merge it and give the hactober fest tag and i will give u another pull request if you merge it and i will work for your repo also please add it.

Quick sort is added#24

---

Dijkstra/dijkstraAlgo.cpp

This program simulates Dijkstra's algorithm for finding shortest paths in directed weighted graphs, allowing users to dynamically add edges, detect cycles, and calculate paths interactively.

dijkstra algo

---

Sorting/SelectionSort.java

hello @Kuwarsaab 
i successfully added the code of selection sort in your sorting folder without any merging confilct
kindly,consider this PR  and merge it under the hacktoberfest2024.

to add "Selection sort algorithm" in java #23

---

Sorting/Bucketsort.java

Hi, added the the sorting process and here the user will input the array of numbers, and the program will dynamically create buckets based on the values. Please merge it and give **hactoberfest** tag please  and your repo is quite good so that's why i want to more contribute on it . so please accept my proposal..

Bucketsort.java added #29

---

Sorting/Insertion Sort.java

Added a Insertion Sort Algorithm in Java Programming Language.

Create Insertion Sort.java

---

Sorting/Quick Sort.java

Added Quick Sort Algorithm in Java Programming Language.

Create Quick Sort.java

---

Sorting/Countingsort.java

counting sort is added in sorting folder and it create a counting array (count[]) to store the frequency of each element from the input array. The size of this array is max + 1, where max is the largest number in the input.  please merge it and give the **hactoberfest** tag please..

Counting Sort is added #34

---

Range_Queries/Segment_tree.cpp

Added code implements a Segment Tree data structure that supports point updates and range queries. This implementation is generic, allowing for different types of nodes and updates by simply changing the Node and Update structures. 
**Please Pull for Hacktoberfest 2024**

Added a range query algorithm involving segment tree. 

---

factorial.c++

added the factorial program. please review and merge it . @Kuwarsaab also please add hactoberfest-accepted and hactoberfest label and tags

added factorial number program in c++

---

Rahul.html

Added a simple website code in an empty file

Added something in a empty file

---

FloydWarshall/floydWarshall.cpp

Floyd-Warshall algorithm Simulator for finding the shortest path between all pairs of nodes in a weighted graph. Its a user interactive simulator, which will ask user to choose options.

Floydwarshall algorithm

---

fibonacci.c++

Added Fibonacci Series Program in c++

---

Threesum.cpp

I have added c++ Code for 3 sum .please review the code @Kuwarsaab

Add 3 Sum C++ implementation

---

minimum.cpp

please merge this and label it as hacktoberfest accepted.

The program is done

---

Factorial.java

Program to calculate factorial of a number

Created a  Factorial program in java

---

palindrome.java

Program to check a number is palindrome or not.

Created palindrome program in java

---

Binary_Tree.cpp.cpp

#88
@Kuwarsaab please add labels as well .
Thank you

Added a cpp program on topic Binary Tree

---

fibonacci.java

Program to find a term in the fibonacci sequence.

Created a  fibonacci program in java.

---

String_palindrome.java

Program to check if the entered String is palindrome or not.

Created a String palindrome program in java.

---

30_Areas_caluclator.py

it helps in caluclating the are of the 30 shapes and also helps in giving the volume and the perimeter based on you inputs

30 shapes area calculator

---

Python/Encryption And Decryption.py

Create Encryption And Decryption.py

---

Graph/graphnew.java

graphnew.java
